### ISSUE TITLE
com.example.parsejsonretrofitgsonexample.databinding.ActivityNestedJsonBinding is missing 

### ISSUE THREAD

**Issue by mrityunjaya9247** [johncodeos-blog/ParseJSONRetrofitConvertersExample#1]
Hi Looks like com.example.parsejsonretrofitgsonexample.databinding.ActivityNestedJsonBinding
is missing in the repo could you please check.

**Comment by johncodeos** [comment]
Yeah, you're right, now is fixed and updated! Thank you!

**Comment by mrityunjaya9247** [comment]
The path "com.example.parsejsonretrofitgsonexample.databinding" is not found still. Is the Class ActivityNestedJsonBinding not used anymore?

**Comment by johncodeos** [comment]
Remove the 'import .....' line that is in red color, and add it again

**Comment by mrityunjaya9247** [comment]
![image](https://user-images.githubusercontent.com/79924859/120072430-85b66680-c0b1-11eb-9c33-15deb3842f46.png)



Not found in Github Repot

**Comment by johncodeos** [comment]
Of course, cause ViewBinding generates the file. Check [this](https://johncodeos.com/how-to-use-view-binding-in-android-using-kotlin/) article that I have about ViewBinding to understand what I'm talking about.

**Comment by mrityunjaya9247** [comment]
Cool. Understood now. Thanks.
